AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  FibonacciFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs22.x
      InlineCode: |
        exports.handler = async (event) => {
          // Log the incoming event
          console.log('Event received:', JSON.stringify(event));
          
          // Random log message
          console.log('Processing Fibonacci calculation at:', new Date().toISOString());
          
          const number = event.number || 0;
          
          // Calculate Fibonacci
          const calculateFibonacci = (n) => {
            if (n <= 1) return n;
            return calculateFibonacci(n - 1) + calculateFibonacci(n - 2);
          };
          
          const result = calculateFibonacci(number);
          
          // Log and return the result
          console.log('Calculated Fibonacci result:', result);
          
          return {
            statusCode: 200,
            body: JSON.stringify({
              input: number,
              fibonacci: result
            })
          };
        };
      Description: A Lambda function that calculates Fibonacci numbers
      MemorySize: 128
      Timeout: 30
      
Outputs:
  FibonacciFunction:
    Description: Fibonacci Lambda Function ARN
    Value: !GetAtt FibonacciFunction.Arn
